# Generated by Django 5.0.4 on 2024-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_usermember2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
