# Generated by Django 5.0.4 on 2024-05-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_departmentapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='pending_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
