# Generated by Django 5.0.4 on 2024-05-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_usermember_pending_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='pending_department',
        ),
    ]
