# Generated by Django 5.0.4 on 2024-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_usermember_pending_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
