# Generated by Django 5.0.4 on 2024-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_department_user_departmentapprovalrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
    ]
