# Generated by Django 5.0.4 on 2024-05-31 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_usermember_waiting_for_department_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentapprovalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
