# Generated by Django 5.0.4 on 2024-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_departmentapprovalrequest_requested_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentApprovalRequest',
        ),
    ]
