# Generated by Django 5.0.4 on 2024-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_delete_departmentapprovalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='temp_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
