# Generated by Django 5.0.4 on 2024-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_pendingworker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingworker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingworker',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
