# Generated by Django 5.0.4 on 2024-06-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_pendingworker_is_approved_pendingworker_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingworker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
