# Generated by Django 5.0.4 on 2024-06-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_pendingworker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingworker',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='pendingworker',
            name='is_pending',
        ),
    ]
