# Generated by Django 5.0.4 on 2024-06-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_pendingworker_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingworker',
            name='user',
        ),
    ]
