# Generated by Django 5.0.4 on 2024-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_userrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerrequest',
            name='worker',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
        migrations.DeleteModel(
            name='WorkerRequest',
        ),
    ]
