# Generated by Django 5.0.4 on 2024-06-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_userrequest_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
