# Generated by Django 5.0.4 on 2024-06-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_workerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usermember')),
            ],
        ),
    ]
