# Generated by Django 5.0.4 on 2024-06-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_userrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='lname',
            new_name='last_name',
        ),
    ]
