# Generated by Django 5.0.4 on 2024-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_delete_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
