# Generated by Django 5.0.4 on 2024-06-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_workerrequest_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usermember')),
                ('worker_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app1.workerrequest')),
            ],
            options={
                'unique_together': {('user', 'worker_request')},
            },
        ),
    ]
