# Generated by Django 5.0.4 on 2024-06-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_notificationrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usermember2'),
        ),
    ]
