# Generated by Django 5.0.4 on 2024-06-12 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_notificationrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
