# Generated by Django 5.0.4 on 2024-06-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_worker_review_delete_notificationrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
