# Generated by Django 5.0.4 on 2024-06-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='worker',
        ),
        migrations.AddField(
            model_name='review',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
