# Generated by Django 5.0.4 on 2024-06-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_remove_review_username_review_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
