# Generated by Django 5.0.4 on 2024-06-14 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app1.usermember2'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app1.usermember'),
        ),
    ]
