# Generated by Django 5.0.4 on 2024-06-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_pendingworker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingworker',
            name='username',
        ),
    ]
