# Generated by Django 5.0.4 on 2024-06-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_pendingworker_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember2',
            old_name='number',
            new_name='contact',
        ),
    ]
