# Generated by Django 5.0.4 on 2024-06-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_rename_number_usermember2_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember2',
            old_name='contact',
            new_name='number',
        ),
    ]
