# Generated by Django 5.0.4 on 2024-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_rename_contact_usermember2_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
