# Generated by Django 5.0.4 on 2024-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_usermember_supporting_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
