# Generated by Django 5.0.4 on 2024-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_alter_usermember_supporting_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember2',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermember2',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
