# Generated by Django 5.0.4 on 2024-06-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_alter_workerrequest_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerrequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usermember'),
        ),
    ]
