# Generated by Django 5.0.4 on 2024-06-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_workerrequest_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember',
            old_name='supporting_documents',
            new_name='supporting_images',
        ),
    ]
