# Generated by Django 5.0.4 on 2024-06-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='usermember2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.usermember2'),
        ),
    ]
