# Generated by Django 5.0.4 on 2024-06-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_request_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worker_first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='worker_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
