# Generated by Django 5.0.4 on 2024-06-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_request_worker_first_name_request_worker_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='worker_first_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='worker_last_name',
        ),
    ]
