# Generated by Django 5.0.4 on 2024-06-23 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_remove_request_worker_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='usermember1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.usermember'),
        ),
    ]
