# Generated by Django 5.0.4 on 2024-06-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_request_usermember1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='usermember1',
            new_name='usermember',
        ),
    ]
