# Generated by Django 5.0.4 on 2024-06-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_rename_usermember1_request_usermember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='usermember',
            new_name='worker',
        ),
    ]
