# Generated by Django 5.0.4 on 2024-06-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_workername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Workername',
        ),
    ]
