# Generated by Django 5.0.4 on 2024-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_acceptedrequest_usermember2'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('deleted', 'Deleted')], default='pending', max_length=10),
        ),
    ]
