# Generated by Django 5.0.4 on 2024-06-26 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_request_confirmed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
