# Generated by Django 5.0.4 on 2024-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_alter_request_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingworker',
            name='supporting_images',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
